export const useModal = () => useState<boolean>('modal', () => false)
export const useEditTaskModal = () => useState<boolean>('editTaskModal', () => false)
export const useDeleteModal = () => useState<boolean>('deleteModal', () => false)
export const useCreateTaskModal = () => useState<boolean>('createTaskModal', () => false)
export const useNewTask = () => useState<string>('newTask', () => '')